id: Expanse Check ServiceNow CMDB
version: -1
name: Expanse Check ServiceNow CMDB
description: |
  Subplaybook for Finding Expanse IPs in ServiceNow CMDB.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bb15edd2-89c7-4b4c-856f-5841c36c40d7
    type: start
    task:
      id: bb15edd2-89c7-4b4c-856f-5841c36c40d7
      version: -1
      name: ""
      description: ''
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 93fe3230-caa9-4faf-875f-5f97e731a3e1
    type: condition
    task:
      id: 93fe3230-caa9-4faf-875f-5f97e731a3e1
      version: -1
      description: ''
      name: Is ServiceNow CMDB Enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: ServiceNow CMDB
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: e0b3c1b6-80fe-4f33-8f95-aa9bfdbeb968
    type: condition
    task:
      id: e0b3c1b6-80fe-4f33-8f95-aa9bfdbeb968
      version: -1
      name: Is Asset On-Prem?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "3"
    scriptarguments:
      value:
        complex:
          root: incident
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: incident.expanseprovider
                iscontext: true
              right:
                value:
                  simple: On Prem
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5c3cc067-c2c5-4f5e-8431-dda66fdbb0e4
    type: condition
    task:
      id: 5c3cc067-c2c5-4f5e-8431-dda66fdbb0e4
      version: -1
      name: IP Address Exists
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "4"
    scriptarguments:
      value:
        complex:
          root: incident.labels
          accessor: ip
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: fd14c144-d53b-4c4f-865a-e6b609f04aec
    type: regular
    task:
      id: fd14c144-d53b-4c4f-865a-e6b609f04aec
      version: -1
      name: Get Network Adaptor CMDB record
      description: Query records for a CMDB class.
      script: "|||servicenow-cmdb-records-list"
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      class:
        simple: cmdb_ci_network_adapter
      limit: {}
      offset: {}
      query:
        simple: ip_address =${incident.labels.ip}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8105cca9-5366-4023-8c5e-3bb8ce963472
    type: regular
    task:
      id: 8105cca9-5366-4023-8c5e-3bb8ce963472
      version: -1
      name: servicenow-cmdb-record-get-by-id
      description: Query attributes and relationship information for a specific record.
      script: "|||servicenow-cmdb-record-get-by-id"
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      class:
        simple: cmdb_ci_network_adapter
      fields: {}
      relation_limit: {}
      relation_offset: {}
      sys_id:
        complex:
          root: ServiceNowCMDB.Records
          accessor: sys_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 9eceafd6-03c1-48e1-87c6-06c836a32fa2
    type: regular
    task:
      id: 9eceafd6-03c1-48e1-87c6-06c836a32fa2
      version: -1
      name: Get CMDB class type and record using the network adaptor
      description: Query attributes and relationship information for a specific record.
      script: "|||servicenow-cmdb-record-get-by-id"
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      class:
        simple: cmdb_ci
      fields: {}
      relation_limit: {}
      relation_offset: {}
      sys_id:
        complex:
          root: ServiceNowCMDB.Record.Attributes.cmdb_ci
          accessor: value
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 3c0553a0-e377-4f03-8bc8-843a8cc6a70d
    type: title
    task:
      id: 3c0553a0-e377-4f03-8bc8-843a8cc6a70d
      version: -1
      name: Playbook End
      type: title
      description: ''
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 1920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 574270ca-cb34-49c2-8c0d-b373a9ab01ce
    type: condition
    task:
      id: 574270ca-cb34-49c2-8c0d-b373a9ab01ce
      version: -1
      name: Network Adaptor exist?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    scriptarguments:
      value:
        simple: ${ServiceNowCMDB.Records}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 8422c9d1-4362-4814-87b0-7d9fef8f0fec
    type: condition
    task:
      id: 8422c9d1-4362-4814-87b0-7d9fef8f0fec
      version: -1
      name: Add asset in CMDB?
      type: condition
      description: ''
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "7"
      "Yes":
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject: null
      body:
        simple: Do you want to add this asset in the CMDB?
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "No"
      - "Yes"
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 55efc89e-56f9-43f6-86fb-6ab4b2ec952f
    type: regular
    task:
      id: 55efc89e-56f9-43f6-86fb-6ab4b2ec952f
      version: -1
      name: Manually add asset in CMDB
      description: The asset is not in your CMDB, please manually add asset in ServiceNow
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 4cab2d04-6806-4a30-8a01-7243c120bb51
    type: regular
    task:
      id: 4cab2d04-6806-4a30-8a01-7243c120bb51
      version: -1
      name: Save CMDB information in Evidence
      description: Convert an array to a nice table display. Usually, from the context.
      scriptName: ToTable
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      columns:
        simple: name,sys_class_name,sys_id,asset.display_value,asset.link,asset.value
      data:
        complex:
          root: ${ServiceNowCMDB.Record
          accessor: Attributes}
      title: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1740
        }
      }
    note: false
    evidencedata:
      description:
        simple: CMDB Evidence
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1935,
        "width": 1300,
        "x": 440,
        "y": 50
      }
    }
  }
inputs: []
outputs:
- contextPath: ServiceNowCMDB.Record
  description: Discovered CI records
  type: unknown
tests:
- No tests
fromversion: 6.0.0
