id: ServiceNow CMDB Search
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: ServiceNow CMDB Search
description: |
  Subplaybook for finding CI records in ServiceNow CMDB.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bb15edd2-89c7-4b4c-856f-5841c36c40d7
    type: start
    task:
      id: bb15edd2-89c7-4b4c-856f-5841c36c40d7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: fb0a9388-cd69-4455-8592-59f584f2c612
    type: regular
    task:
      id: fb0a9388-cd69-4455-8592-59f584f2c612
      version: -1
      name: Search for CMDB record
      description: Query records for a CMDB class.
      script: ServiceNow CMDB|||servicenow-cmdb-records-list
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      class:
        simple: ${inputs.SearchCIClass}
      limit: {}
      offset: {}
      query:
        simple: ${inputs.SearchQueryField}${inputs.SearchQueryOperator}${inputs.SearchQueryValue}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8defe12e-fe93-4785-8eb4-1b73e2ae8e8d
    type: regular
    task:
      id: 8defe12e-fe93-4785-8eb4-1b73e2ae8e8d
      version: -1
      name: Get record by ID
      description: Query attributes and relationship information for a specific record.
      script: ServiceNow CMDB|||servicenow-cmdb-record-get-by-id
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      class:
        simple: ${inputs.SearchCIClass}
      fields: {}
      relation_limit: {}
      relation_offset: {}
      sys_id:
        complex:
          root: ServiceNowCMDB.Records
          accessor: sys_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: dac4dbfd-2c9a-4706-8b26-6e2f8af87e83
    type: regular
    task:
      id: dac4dbfd-2c9a-4706-8b26-6e2f8af87e83
      version: -1
      name: Fetch related CMDB CI by ID
      description: Query attributes and relationship information for a specific record.
      script: ServiceNow CMDB|||servicenow-cmdb-record-get-by-id
      type: regular
      iscommand: true
      brand: ServiceNow CMDB
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      class:
        simple: cmdb_ci
      fields: {}
      relation_limit: {}
      relation_offset: {}
      sys_id:
        complex:
          root: ServiceNowCMDB.Record.Attributes.cmdb_ci
          accessor: value
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 3c0553a0-e377-4f03-8bc8-843a8cc6a70d
    type: title
    task:
      id: 3c0553a0-e377-4f03-8bc8-843a8cc6a70d
      version: -1
      name: Playbook End
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 1920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 5f998f2e-3e91-43fd-8ec7-d55424794f81
    type: condition
    task:
      id: 5f998f2e-3e91-43fd-8ec7-d55424794f81
      version: -1
      name: Do records exist?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    scriptarguments:
      value:
        simple: ${ServiceNowCMDB.Records}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 8422c9d1-4362-4814-87b0-7d9fef8f0fec
    type: condition
    task:
      id: 8422c9d1-4362-4814-87b0-7d9fef8f0fec
      version: -1
      name: Add asset in CMDB?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "7"
      "Yes":
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject: null
      body:
        simple: Do you want to add this asset in the CMDB?
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "No"
      - "Yes"
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 55efc89e-56f9-43f6-86fb-6ab4b2ec952f
    type: regular
    task:
      id: 55efc89e-56f9-43f6-86fb-6ab4b2ec952f
      version: -1
      name: Manually add asset in CMDB
      description: The asset is not in your CMDB, please manually add asset in ServiceNow
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 5c305611-1fa0-49b7-8908-b84eebeffe11
    type: regular
    task:
      id: 5c305611-1fa0-49b7-8908-b84eebeffe11
      version: -1
      name: Save CMDB information in Evidence
      description: Convert an array to a nice table display. Usually, from the context.
      scriptName: ToTable
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      columns:
        simple: name,sys_class_name,sys_id,asset.display_value,asset.link,asset.value
      data:
        complex:
          root: ${ServiceNowCMDB.Record
          accessor: Attributes}
      title: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1740
        }
      }
    note: false
    evidencedata:
      description:
        simple: CMDB Evidence
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1255,
        "width": 1300,
        "x": 440,
        "y": 730
      }
    }
  }
inputs:
- key: SearchCIClass
  value:
    simple: cmdb_ci_network_adapter
  required: false
  description: The CMDB CI class to perform the search on (Defaults to cmdb_ci_network_adapter).
  playbookInputQuery: null
- key: SearchQueryField
  value:
    simple: ip_address
  required: false
  description: The CI field used to perform the query (Defaults to ip_address).
  playbookInputQuery: null
- key: SearchQueryOperator
  value:
    simple: =
  required: false
  description: The operator used to perform the query (Defaults to =).
  playbookInputQuery: null
- key: SearchQueryValue
  value: {}
  required: true
  description: The value used to perform the query.
  playbookInputQuery: null
outputs:
- contextPath: ServiceNowCMDB.Record
  description: Discovered CI records
  type: unknown
