id: 4d6f8382-08a1-493c-8b90-51dfac41fb1b
version: -1
name: Cortex ASM - Vulnerability Management Enrichment
description: This playbook will look up an IP address in Tenable.io.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 99e75dec-0004-47a8-86cf-7784768b7eda
    type: start
    task:
      id: 99e75dec-0004-47a8-86cf-7784768b7eda
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 330b0c51-1a76-42c8-8324-8d2316df50b2
    type: regular
    task:
      id: 330b0c51-1a76-42c8-8324-8d2316df50b2
      version: -1
      name: tenable-io-get-vulnerabilities-by-asset
      description: Gets a list of up to 5000 of the vulnerabilities recorded for a
        specified asset.
      script: Tenable.io|||tenable-io-get-vulnerabilities-by-asset
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      dateRange:
        simple: "30"
      ip:
        simple: ${inputs.IP}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -380,
          "y": 660
        }
      }
    note: true
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 8c7afbc4-bc76-4675-87ed-a8c5e61c15fe
    type: condition
    task:
      id: 8c7afbc4-bc76-4675-87ed-a8c5e61c15fe
      version: -1
      name: Is Tenable.io Enabled?
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Tenable.io
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 53703990-ba87-45dc-8f65-5d69f77498be
    type: title
    task:
      id: 53703990-ba87-45dc-8f65-5d69f77498be
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 33292a48-5944-46a2-8e6b-b738b713588d
    type: condition
    task:
      id: 33292a48-5944-46a2-8e6b-b738b713588d
      version: -1
      name: Do Vulnerability Findings Exist?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "3"
    scriptarguments:
      value:
        complex:
          root: TenableIO.Vulnerabilities
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: TenableIO.Vulnerabilities
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -380,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 6468186e-8384-435f-81a7-24e2a0f11e1b
    type: regular
    task:
      id: 6468186e-8384-435f-81a7-24e2a0f11e1b
      version: -1
      name: Launch Vulnerability Assessment scan manually in https://cloud.tenable.com/
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -380,
          "y": 1150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 0287af65-489b-42fe-812b-5c96ec113a3d
    type: condition
    task:
      id: 0287af65-489b-42fe-812b-5c96ec113a3d
      version: -1
      name: IP address exists?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "1"
    scriptarguments:
      value:
        simple: ${inputs.IP}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -380,
          "y": 460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1645,
        "width": 810,
        "x": -380,
        "y": 50
      }
    }
  }
inputs:
- key: IP
  value: {}
  required: true
  description: IP address to look up in VM tool
  playbookInputQuery: null
outputs: []
tests:
- No tests
fromversion: 6.5.0